use customer_behaviour_database
select * from customer

-- Q1. What is the total revenue generated by male vs. female customers?
select gender, SUM(purchase_amount) as revenue
from customer
group by gender

-- Q2.Which customers used a discount but still spent more than the average purchase amount?
SELECT *
FROM customer
WHERE discount_applied = 'Yes'
AND purchase_amount > (
    SELECT AVG(purchase_amount)
    FROM customer
);

-- Q3. Which are the top 5 products with the highest average review rating?
select item_purchased,avg(review_rating) as "Average_Product_Rating"
from customer
group by item_purchased
order by avg(review_rating) desc
limit 5

-- 04. Compare the average Purchase Amounts between Standard and Express Shipping.
select shipping_type,avg(purchase_amount) as "Average_Purchase_Amt"
from customer
where shipping_type in ("standard","Express")
group by shipping_type

-- 05.Do subscribed customers spend more? Compare average spend and total revenue between subscribers and non-subscribers.
select subscription_status, count(purchase_amount) as "Total_Customer",avg(purchase_amount) as "Average_spend",sum(purchase_amount) as "Total_Revenue"
from customer
group by subscription_status

-- Q6.Which 5 products have the highest percentage of purchases with discounts applied?
SELECT item_purchased,COUNT(CASE WHEN discount_applied = 'Yes' THEN 1 END) * 100.0 / COUNT(*) AS "discount_percentage"
FROM customer
GROUP BY item_purchased
ORDER BY discount_percentage DESC
LIMIT 5;

-- Q7. Segment customers into New, Returning, and Loyal based on their total number of previous purchases, and show the count of each segment.
with customer_type as (
select customer_id,previous_purchases,
case
when previous_purchases=1 then "New"
when previous_purchases between 2 and 10 then "Returning"
else "Loyal"
end as customer_segment
from customer
)
select customer_segment ,count(*) as "Number of Customer"
from customer_type
group by customer_segment

-- Q8. What are the top 3 most purchased products within each category?
SELECT 
    category,
    item_purchased,
    purchase_count
FROM (
    SELECT 
        category,
        item_purchased,
        COUNT(*) AS purchase_count,
        ROW_NUMBER() OVER (
            PARTITION BY category 
            ORDER BY COUNT(*) DESC
        ) AS rn
    FROM customer
    GROUP BY category, item_purchased
) t
WHERE rn <= 3
ORDER BY category, purchase_count DESC;


-- Q9. Are customers who are repeat buyers (more than 5 previous purchases) also likely to subscribe
select subscription_status,count(customer_id) as repeat_buyer
from customer
where previous_purchases>5
group by subscription_status

-- Q10.What is the revenue contribution of each age group?
select age_group,sum(purchase_amount) as Total_revenue
from customer
group by age_group
order by Total_revenue desc

